# ============================================================
# DRC conflict-smoothed scenario
# Endpoint-constrained rebuild preserving the empirical Warsame Q shape
# with grey Warsame UFC points and an empirical uncertainty ribbon.
#
# This is the version intended to match the best conflict plot:
#   * preserve the existing jagged/conflict-interrupted q_value shape;
#   * lock parameter endpoints to early/late literature extrema;
#   * force terminal-zero unsafe-funeral anchors to plateau at zero;
#   * show grey Warsame rolling SDB points only in the community unsafe-funeral panel;
#   * add an uncertainty ribbon derived from uncertainty in the Warsame SDB backbone;
#   * keep orange literature anchors labelled.
#
# Important methodological note:
#   A smooth Stan partial-pooling fit of Q_j(t) will not preserve the jagged
#   empirical conflict shape. Here the empirical Q shape is treated as fixed,
#   which is the intended DRC-conflict specification. The ribbon is therefore
#   uncertainty around that empirical Q backbone rathe                                                r than a re-estimated
#   smooth logistic Q curve.
# ============================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(tibble)
  library(readr)
  library(ggplot2)
})

# ------------------------------------------------------------
# User paths
# ------------------------------------------------------------
parameter_workbook <- "filovirus_model_parameter_table_4_scenarios_with_etu_baseline.xlsx"
parameter_sheet <- "DRC conflict-smoothed"

current_matrix_workbook <- "final_four_scenario_matrices_with 0_1_Qcurves.xlsx"
current_matrix_sheet <- "Middle_DRC_ConflictSmoothed"

sdb_workbook <- "evd_drc_sdb_performance_datasets_pub.xlsx"
if (!file.exists(sdb_workbook)) {
  sdb_workbook_alt <- "evd_drc_sdb_performance_datasets_pub(1).xlsx"
  if (file.exists(sdb_workbook_alt)) sdb_workbook <- sdb_workbook_alt
}
if (!file.exists(sdb_workbook)) {
  sdb_workbook_alt2 <- "evd_drc_sdb_performance_datasets_pub (1).xlsx"
  if (file.exists(sdb_workbook_alt2)) sdb_workbook <- sdb_workbook_alt2
}

out_prefix <- "drc_conflict_endpoint_constrained_preserveQ_directUFC_firstGreyStart"
scenario_name <- "Middle_DRC_ConflictSmoothed"

# ------------------------------------------------------------
# Endpoint logic
# ------------------------------------------------------------
early_endpoint_window_day <- 50
late_endpoint_start_day   <- 325
# Match DRC conflict++ endpoint selection: IPC/PPE uses the late evidence window beginning at day 275.
late_endpoint_start_day_by_parameter <- c(
  "ipc_helper" = 275
)
zero_endpoint_parameters <- c(
  "prob_unsafe_funeral_comm",
  "prob_unsafe_funeral_hosp",
  "prob_unsafe_funeral_etu"
)
zero_tolerance <- 1e-12

# ------------------------------------------------------------
# Warsame reconstruction settings
# ------------------------------------------------------------
provinces_to_average <- c("North Kivu", "Ituri")
success_denominator_mode <- "successful_response_vs_failure"
average_method <- "unweighted_province_mean"  # or "count_weighted"
aggregation_unit <- "epi_week"
sdb_origin_filter <- "all"                    # "all" or "community"

initial_small_n_action <- "zero_success"      # "zero_success", "drop", or "none"
initial_spike_max_day <- 75
initial_spike_min_eligible <- 10
initial_spike_success_threshold <- 0.50

q_smoothing_method <- "rolling4"              # "rolling4" or "none"
rolling_window_n <- 4
rolling_align <- "center"                     # "center" or "trailing"
rolling_use_eligible_weights <- FALSE

# Sparse grey points for the plot only.
plot_sparse_rolling_ufc_dots <- TRUE
plot_rolling_reference_every_n <- rolling_window_n
plot_always_include_end_ufc_dot <- TRUE

# For the community-funeral panel, the fitted line should follow the
# Warsame absolute unsafe-funeral proxy directly after the first orange
# literature anchor. Drop the first few early grey points because these
# precede the intended orange-anchor starting point/transition.
ufc_drop_first_n_grey_points <- 3

# Uncertainty ribbon settings.
# The ribbon is generated by propagating uncertainty in the empirical Warsame
# response backbone through the fixed endpoint mapping.
q_sd_min <- 0.015
q_sd_max <- 0.12
q_ribbon_z <- 1.64  # approx 90% interval, matching q5/q95 convention

# ------------------------------------------------------------
# Parameter mappings
# ------------------------------------------------------------
param_map <- c(
  "prob_hospitalised_genPop; prob_hospitalised_hcw" = "prob_hosp",
  "hospitalisation_delay_factor" = "delay_hosp",
  "p_unsafe_funeral_comm_genPop; p_unsafe_funeral_comm_hcw" = "prob_unsafe_funeral_comm",
  "p_unsafe_funeral_hosp_genPop; p_unsafe_funeral_hcw" = "prob_unsafe_funeral_hosp",
  "p_unsafe_funeral_hosp_genPop; p_unsafe_funeral_hosp_hcw" = "prob_unsafe_funeral_hosp",
  "prob_unsafe_funeral_etu" = "prob_unsafe_funeral_etu",
  "prop_etu" = "prop_etu",
  "ipc_helper; ppe_efficacy_hcw" = "ipc_helper"
)

raw_param_map <- c(
  "delay_hosp" = "delay_hosp",
  "p_hosp" = "prob_hosp",
  "p_ETU" = "prop_etu",
  "latent_IPC" = "ipc_helper",
  "p_unsafe_funeral_comm" = "prob_unsafe_funeral_comm",
  "p_unsafe_funeral_hosp" = "prob_unsafe_funeral_hosp"
)

direction_map <- c(
  "prob_hosp" = "increasing",
  "delay_hosp" = "decreasing",
  "prob_unsafe_funeral_comm" = "decreasing",
  "prob_unsafe_funeral_hosp" = "decreasing",
  "prob_unsafe_funeral_etu" = "flat",
  "prop_etu" = "increasing",
  "ipc_helper" = "increasing"
)

matrix_cols <- c(
  "prob_hosp", "delay_hosp", "prob_unsafe_funeral_comm",
  "prob_unsafe_funeral_hosp", "prob_unsafe_funeral_etu",
  "prop_etu", "ipc_helper"
)

panel_lookup <- c(
  "delay_hosp" = "Delay to hospitalisation",
  "prob_hosp" = "Probability of hospitalisation",
  "prop_etu" = "Proportion in ETU / ETC",
  "ipc_helper" = "Latent IPC / PPE index",
  "prob_unsafe_funeral_comm" = "Unsafe funeral after community death",
  "prob_unsafe_funeral_hosp" = "Unsafe funeral after hospital death",
  "prob_unsafe_funeral_etu" = "Unsafe funeral after ETU death"
)

plot_parameters <- setdiff(matrix_cols, "prob_unsafe_funeral_etu")

# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------
clip01 <- function(x) pmin(1, pmax(0, x))

extract_range <- function(x) {
  x <- as.character(x)
  x <- stringr::str_replace_all(x, "[−—]", "–")
  if (stringr::str_detect(x, "–")) {
    parts <- stringr::str_split_fixed(x, "–", 2)
  } else if (stringr::str_detect(x, "\\d\\s*-\\s*\\d")) {
    parts <- stringr::str_split_fixed(x, "\\s*-\\s*", 2)
  } else {
    nums <- stringr::str_extract_all(x, "[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?")[[1]]
    if (length(nums) == 0) return(c(NA_real_, NA_real_))
    if (length(nums) == 1) return(rep(as.numeric(nums[1]), 2))
    return(as.numeric(nums[1:2]))
  }

  out <- rep(NA_real_, 2)
  for (i in 1:2) {
    nums <- stringr::str_extract_all(parts[i], "[-+]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?")[[1]]
    if (length(nums) > 0) out[i] <- as.numeric(nums[1])
  }
  out
}

parse_anchor_value <- function(x) {
  x <- as.character(x)
  day <- as.numeric(stringr::str_match(x, "relative\\s+day\\s+([0-9.]+)\\s*:")[,2])
  val <- as.numeric(stringr::str_match(x, ":\\s*([0-9.]+)")[,2])
  tibble(relative_day = day, value_used = val)
}

parse_from_description <- function(x, key) {
  pat <- paste0(key, ":\\s*([^;]+)")
  out <- stringr::str_match(as.character(x), pat)[,2]
  stringr::str_squish(out)
}

make_endpoint_values <- function(parameter, lo, hi) {
  direction <- direction_map[[parameter]]
  if (is.na(lo) || is.na(hi)) stop("Missing endpoint for ", parameter)
  if (direction == "increasing") return(c(start = lo, end = hi))
  if (direction == "decreasing") return(c(start = hi, end = lo))
  return(c(start = lo, end = lo))
}

choose_endpoint_row <- function(direction, window, endpoint_type) {
  if (nrow(window) == 0) return(NULL)
  if (direction == "increasing") {
    idx <- if (endpoint_type == "start") which.min(window$value_used) else which.max(window$value_used)
  } else if (direction == "decreasing") {
    idx <- if (endpoint_type == "start") which.max(window$value_used) else which.min(window$value_used)
  } else {
    idx <- which.min(window$relative_day)
  }
  window[idx[1], , drop = FALSE]
}

rolling_mean_ordered <- function(y, k = 4, align = "center", weights = NULL) {
  if (!align %in% c("center", "trailing")) {
    stop("rolling_align must be either 'center' or 'trailing'.")
  }
  if (length(y) == 0) return(numeric(0))
  if (k < 1) stop("Rolling window k must be >= 1.")

  n <- length(y)
  out <- rep(NA_real_, n)
  if (is.null(weights)) weights <- rep(1, n)

  for (i in seq_len(n)) {
    if (align == "trailing") {
      idx <- seq.int(max(1, i - k + 1), i)
    } else {
      left_n <- floor((k - 1) / 2)
      right_n <- (k - 1) - left_n
      idx <- seq.int(max(1, i - left_n), min(n, i + right_n))
    }

    yy <- y[idx]
    ww <- weights[idx]
    ok <- is.finite(yy) & is.finite(ww) & ww > 0
    if (any(ok)) out[i] <- stats::weighted.mean(yy[ok], w = ww[ok])
  }
  out
}

# ------------------------------------------------------------
# Read parameter workbook anchors and ranges
# ------------------------------------------------------------
raw <- readxl::read_excel(parameter_workbook, sheet = parameter_sheet, col_names = FALSE)
names(raw)[1:7] <- c("Section","Parameter","Symbol","Description","Value_range","Reference","URL")

summary_ranges <- raw %>%
  filter(.data$Section == "Time-varying response") %>%
  filter(.data$Parameter %in% names(param_map)) %>%
  mutate(
    parameter = unname(param_map[.data$Parameter]),
    range_pair = lapply(.data$Value_range, extract_range),
    endpoint_low = vapply(range_pair, function(z) z[1], numeric(1)),
    endpoint_high = vapply(range_pair, function(z) z[2], numeric(1))
  ) %>%
  select(parameter, endpoint_low, endpoint_high, Value_range, Reference, URL)

anchors <- raw %>%
  filter(.data$Section == "Time-varying curve anchors") %>%
  filter(!is.na(.data$Parameter), .data$Parameter != "Orange-point fitted anchors") %>%
  mutate(
    anchor_id = as.character(.data$Parameter),
    raw_parameter = parse_from_description(.data$Description, "Parameter"),
    parameter = unname(raw_param_map[raw_parameter]),
    fit_role = parse_from_description(.data$Description, "fit role"),
    evidence_tier = parse_from_description(.data$Description, "evidence tier")
  ) %>%
  bind_cols(parse_anchor_value(.$Value_range)) %>%
  filter(.data$parameter %in% matrix_cols) %>%
  filter(is.finite(.data$relative_day), is.finite(.data$value_used)) %>%
  mutate(value_low = value_used, value_high = value_used)

eligible_endpoint_anchors <- anchors %>%
  filter(!is.na(parameter), is.finite(value_used), is.finite(relative_day)) %>%
  filter(is.na(fit_role) | !fit_role %in% c("reference_only", "plot_only"))

endpoint_anchor_values <- eligible_endpoint_anchors %>%
  group_by(parameter) %>%
  group_modify(function(.x, .y) {
    p <- .y$parameter[[1]]
    direction <- unname(direction_map[p])
    early_window <- .x %>% filter(relative_day <= early_endpoint_window_day)
    late_cutoff <- if (p %in% names(late_endpoint_start_day_by_parameter)) {
      unname(late_endpoint_start_day_by_parameter[p])
    } else {
      late_endpoint_start_day
    }
    late_window  <- .x %>% filter(relative_day >= late_cutoff)
    start_row <- choose_endpoint_row(direction, early_window, "start")

    zero_rows <- if (p %in% zero_endpoint_parameters) {
      .x %>% filter(abs(value_used) <= zero_tolerance)
    } else {
      .x[0, , drop = FALSE]
    }

    if (nrow(zero_rows) > 0) {
      end_row <- zero_rows %>% arrange(desc(relative_day)) %>% slice(1)
      end_source <- "terminal_zero_anchor_anywhere"
    } else {
      end_row <- choose_endpoint_row(direction, late_window, "end")
      end_source <- if (!is.null(end_row)) {
        if (p %in% names(late_endpoint_start_day_by_parameter)) {
          paste0("parameter_specific_late_window_extreme_anchor_day", late_cutoff)
        } else {
          "late_window_extreme_anchor"
        }
      } else NA_character_
    }

    tibble(
      start_anchor_day = if (!is.null(start_row)) start_row$relative_day[[1]] else NA_real_,
      end_anchor_day   = if (!is.null(end_row))   end_row$relative_day[[1]]   else NA_real_,
      start_anchor_value = if (!is.null(start_row)) start_row$value_used[[1]] else NA_real_,
      end_anchor_value   = if (!is.null(end_row))   end_row$value_used[[1]]   else NA_real_,
      start_endpoint_source = if (!is.null(start_row)) "early_window_extreme_anchor" else NA_character_,
      end_endpoint_source   = end_source
    )
  }) %>%
  ungroup()

endpoint_table <- summary_ranges %>%
  filter(parameter %in% matrix_cols) %>%
  left_join(endpoint_anchor_values, by = "parameter") %>%
  mutate(
    fallback_start_value = mapply(function(p, lo, hi) make_endpoint_values(p, lo, hi)[["start"]],
                                  parameter, endpoint_low, endpoint_high),
    fallback_end_value = mapply(function(p, lo, hi) make_endpoint_values(p, lo, hi)[["end"]],
                                parameter, endpoint_low, endpoint_high),
    start_value = if_else(is.finite(start_anchor_value), start_anchor_value, fallback_start_value),
    end_value   = if_else(is.finite(end_anchor_value),   end_anchor_value,   fallback_end_value),
    start_endpoint_source = if_else(is.na(start_endpoint_source), "summary_range_fallback_no_early_anchor", start_endpoint_source),
    end_endpoint_source   = if_else(is.na(end_endpoint_source),   "summary_range_fallback_no_late_anchor",  end_endpoint_source),
    endpoint_source = paste(start_endpoint_source, end_endpoint_source, sep = " / "),
    direction = unname(direction_map[parameter])
  )

readr::write_csv(endpoint_table, paste0(out_prefix, "_endpoint_table_used.csv"))

# ------------------------------------------------------------
# Preserve the existing DRC conflict Q shape from the current matrix
# ------------------------------------------------------------
current <- readxl::read_excel(current_matrix_workbook, sheet = current_matrix_sheet) %>%
  mutate(across(everything(), as.numeric))

if (!"q_value" %in% names(current) || all(is.na(current$q_value))) {
  stop("Current matrix lacks a usable q_value column; use the upstream DRC conflict script first.")
}

q <- current$q_value
q <- q - min(q, na.rm = TRUE)
q <- q / max(q, na.rm = TRUE)
q <- clip01(q)

matrix_out <- current %>%
  mutate(
    scenario = scenario_name,
    time_index = row_number(),
    q_value = q
  ) %>%
  select(scenario, time_index, tau, relative_day, q_value)

# ------------------------------------------------------------
# Reconstruct Warsame SDB points for grey UFC overlay and Q uncertainty
# ------------------------------------------------------------
if (!file.exists(sdb_workbook)) {
  stop("Cannot find Warsame SDB workbook: ", sdb_workbook)
}

admin_units <- readxl::read_excel(sdb_workbook, sheet = "admin_units") %>%
  mutate(hz = as.character(hz), province = as.character(province))

sdb_dataset <- readxl::read_excel(sdb_workbook, sheet = "sdb_dataset") %>%
  mutate(
    hz = as.character(hz),
    outcome_lshtm = tolower(trimws(as.character(outcome_lshtm))),
    origin_cat = tolower(trimws(as.character(origin_cat))),
    date = as.Date(date)
  )

province_lookup <- admin_units %>% distinct(hz, province)

sdb_prov <- sdb_dataset %>%
  left_join(province_lookup, by = "hz") %>%
  filter(province %in% provinces_to_average) %>%
  filter(!is.na(date))

if (sdb_origin_filter == "community") {
  sdb_prov <- sdb_prov %>% filter(origin_cat == "community")
}
if (nrow(sdb_prov) == 0) stop("No SDB rows remain after province/origin filtering.")

sdb_start_date <- min(sdb_prov$date, na.rm = TRUE)

if (aggregation_unit == "epi_week") {
  sdb_prov <- sdb_prov %>%
    mutate(
      bin_start = date - as.integer(format(date, "%u")) + 1,
      bin_mid_date = bin_start + 3,
      bin_label = paste0(epi_year, "-W", sprintf("%02d", as.integer(epi_week)))
    )
} else {
  stop("This script expects aggregation_unit = 'epi_week'.")
}

prov_binned <- sdb_prov %>%
  group_by(province, bin_label, bin_start, bin_mid_date) %>%
  summarise(
    n_success = sum(outcome_lshtm == "success", na.rm = TRUE),
    n_successful_response = sum(outcome_lshtm %in% c("success", "sdb not needed"), na.rm = TRUE),
    n_failure = sum(outcome_lshtm == "failure", na.rm = TRUE),
    n_false_alert = sum(outcome_lshtm == "false alert", na.rm = TRUE),
    n_unclear = sum(outcome_lshtm == "unclear", na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    n_eligible = case_when(
      success_denominator_mode == "successful_response_vs_failure" ~ n_successful_response + n_failure,
      TRUE ~ NA_real_
    ),
    prop_success_raw = if_else(n_eligible > 0, n_successful_response / n_eligible, NA_real_),
    relative_day = as.numeric(bin_mid_date - sdb_start_date),
    small_n_initial_spike = initial_small_n_action != "none" &
      relative_day <= initial_spike_max_day &
      n_eligible < initial_spike_min_eligible &
      prop_success_raw >= initial_spike_success_threshold,
    prop_success_clean = case_when(
      initial_small_n_action == "zero_success" & small_n_initial_spike ~ 0,
      initial_small_n_action == "drop" & small_n_initial_spike ~ NA_real_,
      TRUE ~ prop_success_raw
    )
  ) %>%
  filter(!is.na(prop_success_clean)) %>%
  arrange(province, bin_mid_date)

sdb_avg <- prov_binned %>%
  group_by(bin_label, bin_start, bin_mid_date) %>%
  summarise(
    relative_day = as.numeric(first(bin_mid_date) - sdb_start_date),
    n_provinces_with_data = n_distinct(province),
    n_eligible_sum = sum(n_eligible, na.rm = TRUE),
    prop_success_unweighted = mean(prop_success_clean, na.rm = TRUE),
    prop_success_count_weighted = if_else(
      sum(n_eligible, na.rm = TRUE) > 0,
      weighted.mean(prop_success_clean, w = pmax(n_eligible, 0), na.rm = TRUE),
      NA_real_
    ),
    any_initial_spike_adjusted = any(small_n_initial_spike),
    .groups = "drop"
  ) %>%
  arrange(bin_mid_date) %>%
  mutate(
    prop_success_avg_raw = case_when(
      average_method == "unweighted_province_mean" ~ prop_success_unweighted,
      average_method == "count_weighted" ~ prop_success_count_weighted,
      TRUE ~ NA_real_
    )
  ) %>%
  filter(is.finite(relative_day), is.finite(prop_success_avg_raw), n_eligible_sum > 0) %>%
  arrange(relative_day) %>%
  mutate(
    prop_success_avg = if (q_smoothing_method == "rolling4") {
      clip01(rolling_mean_ordered(
        y = prop_success_avg_raw,
        k = rolling_window_n,
        align = rolling_align,
        weights = if (rolling_use_eligible_weights) n_eligible_sum else NULL
      ))
    } else {
      prop_success_avg_raw
    },
    p_unsafe_funeral_comm_proxy = clip01(1 - prop_success_avg),
    sdb_obs_sd = pmax(
      q_sd_min,
      pmin(
        q_sd_max,
        sqrt(pmax(prop_success_avg * (1 - prop_success_avg), 1e-6) / pmax(n_eligible_sum, 1))
      )
    )
  )

# Add a start support point for interpolation if needed.
sdb_for_uncertainty <- bind_rows(
  tibble(
    relative_day = 0,
    prop_success_avg = 0,
    p_unsafe_funeral_comm_proxy = 1,
    sdb_obs_sd = q_sd_max,
    n_eligible_sum = 0,
    bin_mid_date = sdb_start_date,
    bin_label = "START"
  ),
  sdb_avg %>% select(relative_day, prop_success_avg, p_unsafe_funeral_comm_proxy,
                     sdb_obs_sd, n_eligible_sum, bin_mid_date, bin_label)
) %>%
  arrange(relative_day) %>%
  distinct(relative_day, .keep_all = TRUE)

q_scale_max <- max(sdb_for_uncertainty$prop_success_avg, na.rm = TRUE)
if (!is.finite(q_scale_max) || q_scale_max <= 0) {
  q_scale_max <- 1
}

# Interpolate Q uncertainty onto matrix days.
q_sd_raw <- clip01(sdb_for_uncertainty$sdb_obs_sd / q_scale_max)
q_sd_interp <- approx(
  x = sdb_for_uncertainty$relative_day,
  y = q_sd_raw,
  xout = matrix_out$relative_day,
  rule = 2,
  ties = mean
)$y
q_sd_interp <- pmax(q_sd_min, pmin(q_sd_max, q_sd_interp))

q_low <- clip01(q - q_ribbon_z * q_sd_interp)
q_high <- clip01(q + q_ribbon_z * q_sd_interp)


# ------------------------------------------------------------
# Direct Warsame UFC support for community-funeral panel
# ------------------------------------------------------------
# For the direct revised-methodology DRC conflict specification, community
# unsafe funerals are anchored to the first available Warsame grey point, not
# the first orange literature anchor.
#
# Rationale:
#   p_unsafe_funeral_comm is the one parameter for which we have a direct
#   empirical time-series proxy on the absolute scale:
#
#       p_unsafe_funeral_comm(t) = 1 - successful SDB response(t)
#
#   Therefore its direct curve should begin at the first Warsame rolling point
#   and then follow the Warsame rolling proxy. This prevents the curve from
#   appearing to get worse than its own baseline before the conflict period.
#
# The orange UFC anchors remain plotted for audit/context, but they do not
# set the direct Warsame-UFC start point.
sdb_ufc_after_start <- sdb_avg %>%
  filter(is.finite(relative_day), is.finite(p_unsafe_funeral_comm_proxy)) %>%
  arrange(relative_day)

ufc_direct_support <- sdb_ufc_after_start %>%
  transmute(
    relative_day = relative_day,
    value = p_unsafe_funeral_comm_proxy,
    support_type = if ("is_drc_plusplus_collapse_point" %in% names(sdb_ufc_after_start)) {
      if_else(is_drc_plusplus_collapse_point,
              "warsame_rolling_proxy_drc_plusplus_forced_collapse",
              "warsame_rolling_proxy")
    } else {
      "warsame_rolling_proxy"
    },
    n_eligible_sum = n_eligible_sum
  ) %>%
  filter(is.finite(relative_day), is.finite(value)) %>%
  arrange(relative_day) %>%
  group_by(relative_day) %>%
  summarise(
    value = mean(value, na.rm = TRUE),
    support_type = paste(unique(support_type), collapse = ";"),
    n_eligible_sum = if (all(is.na(n_eligible_sum))) NA_real_ else sum(n_eligible_sum, na.rm = TRUE),
    .groups = "drop"
  )

if (nrow(ufc_direct_support) < 2) {
  stop("Not enough direct Warsame UFC support points.")
}

ufc_direct_curve <- approx(
  x = ufc_direct_support$relative_day,
  y = ufc_direct_support$value,
  xout = matrix_out$relative_day,
  rule = 2,
  ties = mean
)$y
ufc_direct_curve <- clip01(ufc_direct_curve)

readr::write_csv(ufc_direct_support, paste0(out_prefix, "_ufc_direct_warsame_support_used.csv"))

# ------------------------------------------------------------
# Build endpoint-locked matrix and uncertainty long table
# ------------------------------------------------------------
matrix_uncertainty_long <- list()

for (p in matrix_cols) {
  e <- endpoint_table %>% filter(parameter == p) %>% slice(1)

  if (nrow(e) == 0) {
    matrix_out[[p]] <- NA_real_
    next
  }

  if (p == "prob_unsafe_funeral_comm") {
    # For DRC conflict, community unsafe funerals are the absolute Warsame
    # unsafe-funeral proxy from the first grey Warsame point. This exactly mirrors
    # the grey SDB points and deliberately has no CI ribbon.
    mean_vec <- ufc_direct_curve
    q5_vec <- mean_vec
    q95_vec <- mean_vec
  } else if (e$direction == "flat") {
    mean_vec <- rep(e$start_value, nrow(matrix_out))
    q5_vec <- mean_vec
    q95_vec <- mean_vec
  } else {
    mean_vec <- e$start_value + (e$end_value - e$start_value) * q
    low_candidate <- e$start_value + (e$end_value - e$start_value) * q_low
    high_candidate <- e$start_value + (e$end_value - e$start_value) * q_high
    q5_vec <- pmin(low_candidate, high_candidate)
    q95_vec <- pmax(low_candidate, high_candidate)

    if (e$end_endpoint_source == "terminal_zero_anchor_anywhere" && is.finite(e$end_anchor_day)) {
      plateau_idx <- matrix_out$relative_day >= e$end_anchor_day
      mean_vec[plateau_idx] <- e$end_value
      q5_vec[plateau_idx] <- e$end_value
      q95_vec[plateau_idx] <- e$end_value
    }
  }

  matrix_out[[p]] <- mean_vec

  matrix_uncertainty_long[[p]] <- tibble(
    parameter = p,
    relative_day = matrix_out$relative_day,
    mean = mean_vec,
    q5 = q5_vec,
    q95 = q95_vec
  )
}

matrix_uncertainty_long <- bind_rows(matrix_uncertainty_long)

readr::write_csv(matrix_out, paste0(out_prefix, "_matrix.csv"))
readr::write_csv(matrix_uncertainty_long, paste0(out_prefix, "_matrix_with_uncertainty_long.csv"))
readr::write_csv(sdb_avg, paste0(out_prefix, "_warsame_sdb_points_used.csv"))
readr::write_csv(prov_binned, paste0(out_prefix, "_province_binned_sdb_success.csv"))

# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
plot_long <- matrix_uncertainty_long %>%
  filter(parameter %in% plot_parameters) %>%
  mutate(panel_title = factor(unname(panel_lookup[parameter]), levels = panel_lookup[plot_parameters]))

anchor_plot <- anchors %>%
  filter(parameter %in% plot_parameters) %>%
  mutate(panel_title = factor(unname(panel_lookup[parameter]), levels = panel_lookup[plot_parameters]))

# Grey Warsame points use the same post-start, post-drop source as the direct
# p_unsafe_funeral_comm curve. They are sparse only for visual clarity; the
# black line uses all points in ufc_direct_support.
sdb_plot <- sdb_ufc_after_start %>%
  arrange(relative_day) %>%
  mutate(
    rolling_ref_row = row_number(),
    keep_sparse_ref = case_when(
      !plot_sparse_rolling_ufc_dots ~ TRUE,
      plot_always_include_end_ufc_dot & rolling_ref_row == n() ~ TRUE,
      TRUE ~ ((rolling_ref_row - 1L) %% plot_rolling_reference_every_n) == 0L
    )
  ) %>%
  filter(keep_sparse_ref) %>%
  transmute(
    relative_day = relative_day,
    value = p_unsafe_funeral_comm_proxy,
    n_eligible_sum = n_eligible_sum,
    panel_title = factor("Unsafe funeral after community death", levels = panel_lookup[plot_parameters])
  )

p <- ggplot() +
  geom_ribbon(
    data = plot_long %>% filter(parameter != "prob_unsafe_funeral_comm"),
    aes(x = relative_day, ymin = q5, ymax = q95),
    alpha = 0.18,
    fill = "grey60"
  ) +
  geom_line(
    data = plot_long,
    aes(x = relative_day, y = mean),
    linewidth = 0.9,
    colour = "black"
  ) +
  geom_point(
    data = sdb_plot,
    aes(x = relative_day, y = value, size = n_eligible_sum),
    inherit.aes = FALSE,
    colour = "grey45",
    alpha = 0.75
  ) +
  scale_size_continuous(name = "Warsame eligible SDBs", range = c(1.2, 4.0), guide = "none") +
  geom_errorbar(
    data = anchor_plot,
    aes(x = relative_day, ymin = value_low, ymax = value_high),
    width = 0,
    colour = "orange3",
    linewidth = 0.55
  ) +
  geom_point(
    data = anchor_plot,
    aes(x = relative_day, y = value_used),
    colour = "orange3",
    size = 2.1
  ) +
  geom_text(
    data = anchor_plot,
    aes(x = relative_day, y = value_used, label = anchor_id),
    colour = "orange4",
    size = 2.4,
    hjust = -0.05,
    vjust = -0.6,
    check_overlap = TRUE
  ) +
  facet_wrap(~panel_title, scales = "free_y", ncol = 2) +
  labs(
    title = "DRC conflict-smoothed: endpoint-constrained empirical-Q rebuild",
    subtitle = "Conflict Q preserved for response parameters; community unsafe-funeral curve follows Warsame proxy directly from the first grey Warsame point; no UFC ribbon",
    x = "Relative day",
    y = "Parameter value"
  ) +
  theme_bw(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), panel.grid.minor = element_blank())

ggsave(paste0(out_prefix, "_endpoint_constrained_plot.png"), p, width = 11, height = 8, dpi = 300)
ggsave(paste0(out_prefix, "_endpoint_constrained_plot.pdf"), p, width = 11, height = 8)

readr::write_csv(
  anchors %>% select(any_of(c("anchor_id", "parameter", "relative_day", "value_used", "value_low", "value_high",
                             "fit_role", "evidence_tier", "Reference", "URL"))),
  paste0(out_prefix, "_anchor_table_used.csv")
)

message("Done: ", out_prefix)
